### ISSUE TITLE
flux_local_exec doesn't work with flux handle's reactor

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core-v0.11#14]
This may be an intended behavior, but some clarification would be helpful.

It turns out `flux_local_exec` doesn't work with the reactor associated with a flux handle returned from `flux_open ()` for an API client. For example, the following will fail:

```c
   if (!(h = flux_open (NULL, 0)))
        log_err_exit ("flux_open");
    char *av[] = { "/bin/hostname", NULL };
    flux_cmd_t *cmd = flux_cmd_create (1, av, NULL);
    flux_reactor_t *r = flux_get_reactor (h);
    if (!flux_local_exec (r, 0, cmd, &ops)) {
        printf ("failed\n");
        exit (1);
    }
```

While the following will work:
```c
   if (!(h = flux_open (NULL, 0)))
        log_err_exit ("flux_open");
    char *av[] = { "/bin/hostname", NULL };
    flux_cmd_t *cmd = flux_cmd_create (1, av, NULL);
    flux_reactor_t *r = flux_reactor_create (FLUX_REACTOR_SIGCHLD);
    if (!flux_local_exec (r, 0, cmd, &ops)) {
        printf ("failed\n");
        exit (1);
    }
```

This is because `flux_get_reactor (h)` creates a reactor with `flux_reactor_create (0)` which doesn't pass an argument check in [here](https://github.com/flux-framework/flux-core-v0.11/blob/master/src/common/libflux/reactor.c#L940).

I can always create a new reactor for my `flux-job-debug` front end but it maybe better to be able to use the flux handle's reactor if possible?

**Comment by grondo** [comment]
For now I wonder if this would work:

```c
    flux_reactor_t *r = flux_reactor_create (FLUX_REACTOR_SIGCHLD);
    h = flux_open (NULL, 0);
    flux_set_reactor (h, r);
```

I understand why `flux_get_reactor(3)` doesn't call `flux_reactor_create(3)` with `FLUX_REACTOR_SIGCHLD` by default, but perhaps we can figure out some way for the "main" flux API handle to get an ev loop capable of creating subprocesses by default.

**Comment by garlick** [comment]
That should work, or use the broker to start processes since it's reactor
has that capability.

The constraint is that only one reactor per process can have it.

**Comment by grondo** [comment]
>  or use the broker to start processes since it's reactor has that capability.

Actually, that would work in the v0.11 case, since that version is only single user (if you are sure to copy the current environment, working directory, etc to the remote subprocess), though it isn't the right solution for multi-user capable flux obvoiously.

> The constraint is that only one reactor per process can have it.

Probably multiple reactor per API client process is the uncommon case. It would be nice if for the common case a "default loop" was created as the reactor for the first flux_t handle created by a process.

However, if that is dangerous perhaps a new flag to `flux_open(3)`?

**Comment by garlick** [comment]
True, and modules which share the broker process have their reactor
pre-created I believe.

**Comment by dongahn** [comment]
> I understand why flux_get_reactor(3) doesn't call flux_reactor_create(3) with FLUX_REACTOR_SIGCHLD by default, but perhaps we can figure out some way for the "main" flux API handle to get an ev loop capable of creating subprocesses by default.

Yes, this is my current approach. 

> or use the broker to start processes since it's reactor
has that capability.

This means to use `flux_rexec ()`? I already tested this and this works. If I were to do it this way, I will need to make sure that the local rank is passed to this function since I will have to pass a pipe FD to wreckrun.

> The constraint is that only one reactor per process can have it.

Understood. I'm fine with the first solution. I will try to add a comment to `flux_local_exec` in its header file about this constraint. (Maybe we need a caveat for `flux_open` as well...)

**Comment by grondo** [comment]
> I will need to make sure that the local rank is passed to this function since I will have to pass a pipe FD to wreckrun.

You can't pass a pipe directly using `flux_rexec()`, however you can use `flux_cmd_add_channel (cmd, name)` to add a "channel" which will be presented as an fd in the remote subprocess with an environment variable `name` set to the fd number.

If you go this route, make sure you set the current environment and working directory in the remote process, or it will inherit from flux-broker instead of the user's current environment.

**Comment by dongahn** [comment]
> You can't pass a pipe directly using flux_rexec(), however you can use flux_cmd_add_channel (cmd, name) to add a "channel" which will be presented as an fd in the remote subprocess with an environment variable name set to the fd number.

Yes, I saw this channel primitive and thought this was great! 

> If you go this route, make sure you set the current environment and working directory in the remote process, or it will inherit from flux-broker instead of the user's current environment.

Yes, I also noticed those requirements. So my current approach is `flux_local_exec ()` by explicitly setting my reactor to avoid these. (Please this should be faster, as I'm saying one more hop).

**Comment by grondo** [comment]
> my current approach is flux_local_exec () by explicitly setting my reactor to avoid these.

Ah, ok. Good choice, I must have misunderstood.

I was initially stumped for how to add support for "JOBID_FD" environment variable to wreckrun, because as it turns out Lua doesn't seem to have the equivalent of `fdopen(3)` or even a concept of low level file descriptors. Luckily, it seems like `open ("/proc/self/fd/JOBID_FD", "w"` will work, but we should test this once you have a working command.

**Comment by dongahn** [comment]
> I was initially stumped for how to add support for "JOBID_FD" environment variable to wreckrun, because as it turns out Lua doesn't seem to have the equivalent of fdopen(3) or even a concept of low level file descriptors. Luckily, it seems like open ("/proc/self/fd/JOBID_FD", "w" will work, but we should test this once you have a working command.

Ah. Great hint! I am not there yet but I will soon get there to test.

**Comment by dongahn** [comment]
> Luckily, it seems like open ("/proc/self/fd/JOBID_FD", "w" will work, but we should test this once you have a working command.

So, for testing I modified `wreck.lua`

```diff
diff --git a/src/bindings/lua/wreck.lua b/src/bindings/lua/wreck.lua
index d2fa3223..0df96521 100644
--- a/src/bindings/lua/wreck.lua
+++ b/src/bindings/lua/wreck.lua
@@ -525,6 +525,13 @@ function wreck:createjob ()
         self.lwj_paths [resp.jobid] = resp.kvs_path
         kvs_paths [resp.jobid] = resp.kvs_path
     end
+    local env = posix.getenv ()
+    if env["FLUX_WRECKRUN_JOBID_FD"] then
+        local fd = env["FLUX_WRECKRUN_JOBID_FD"]
+        os.execute ("ls -l /proc/self/fd/")
+        local s = assert (io.open ("/proc/self/fd/"..fd, "w"))
+        s:write (tostring (resp.jobid))
+    end
     return resp.jobid, resp.kvs_path
 end
```

But I'm getting "No such device or address" error. 
```
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 0 -> socket:[553903]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 1 -> socket:[553905]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 11 -> socket:[553905]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 13 -> socket:[553907]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 15 -> socket:[553909]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 2 -> socket:[553907]
lr-x------ 1 ahn1 ahn1 64 May 22 01:41 3 -> /proc/51187/fd
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 7 -> anon_inode:[eventfd]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 9 -> socket:[553903]
lua: /usr/share/lua/5.2/wreck.lua:532: /proc/self/fd/15: No such device or address
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.2/wreck.lua:532: in function 'createjob'
	/usr/libexec/flux/cmd/flux-wreckrun:168: in main chunk
	[C]: in ?
```

The FD=15 was created by `job-debug` using `flux_cmd_add_channel ()` and `flux_local_exec ()`. @grondo: what am I missing in opening up the FD?

**Comment by grondo** [comment]
Hm, your code looks good to me.

I also added support for this to my `wreckrun-job-debug-support` branch, which also has support for the `--jobid=ID` if you want to try there (really not much difference though) If you have your code on a branch, I can take a look as well.

**Comment by dongahn** [comment]
Good to know there is an working code. I will check the differences between the two codes tomorrow.Thanks @grondo.

**Comment by grondo** [comment]
> Good to know there is an working code. I will check the differences between the two codes tomorrow.

@dongahn, sorry didn't mean to imply my code was working. I did a simple test with
```
$ FLUX_WRECKRUN_JOBID_FD=2 flux wreckrun hostname
```
but other than that I didn't have a testcase yet.

**Comment by dongahn** [comment]
@grondo: where did you run your test above? Was it with docker?

I picked your code at [here](https://github.com/flux-framework/flux-core-v0.11/pull/16/commits/853501432e60a3a5e3c97632fc1e95f8dbd530fa) and this fails on my environment. 

```
wreckrun: Error: opening FLUX_WRECKRUN_JOBID_FD=15: /proc/self/fd/15: No such device or address
```

I start to fear this scheme just wouldn't work for Mac oxs with docker? Ugh.

**Comment by dongahn** [comment]
Looking at `/proc/self/fd` as seen by the forked/execed `wreckrun` once again: 

```
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 0 -> socket:[553903]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 1 -> socket:[553905]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 11 -> socket:[553905]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 13 -> socket:[553907]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 15 -> socket:[553909]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 2 -> socket:[553907]
lr-x------ 1 ahn1 ahn1 64 May 22 01:41 3 -> /proc/51187/fd
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 7 -> anon_inode:[eventfd]
lrwx------ 1 ahn1 ahn1 64 May 22 01:41 9 -> socket:[553903]
```

Maybe the problem is because the file descriptors are all socket types. Presumably `flux_cmd_add_channel` uses socket for IO redirection even though the processes are forked/execed with `flux_local_exec`? I will see if I just manually create a pipe, the LUA code works better.

**Comment by grondo** [comment]
> Maybe the problem is because the file descriptors are all socket types.

Hm, that could be, maybe the socket type fd links in /proc/PID/fd do not support open(2).
If the normal pipe(2) works then this is probably the case (and could be a good workaround since we don't need bi-directional here.)

We shouldn't have the same problem on flux-core upstream because `flux job run` or similar will not be written in Lua.

**Comment by dongahn** [comment]
> If the normal pipe(2) works then this is probably the case 

Unfortunately, I couldn't use this: I don't know how to cause the channel callback of the subprocess to be invoked on a manually created pipe like this...

**Comment by grondo** [comment]
> Unfortunately, I couldn't use this: I don't know how to cause the channel callback of the subprocess to be invoked on a manually created pipe like this...

In this case you'd use a normal fd watcher on the read side of the pipe. However, I can't remember how to keep the subprocess code from closing a specific file descriptor besides 0,1,2...

Let me look again and see if I missed something obvious in lua posix to write to an open file descriptor before we spend too much more time on this

**Comment by dongahn** [comment]
If worse comes to the worse, we should consider an alternative scheme like.

- `--print-jobid` option into wreckrun, which then print the jobid into its stdout stream in a well parseable format
- `flux-job-debug` then can extract the jobid from the stdout subprocess callback

Downside is this will add a little bit of performance overhead to the stdout callback. But this overhead is manageable, I think.

**Comment by dongahn** [comment]
> Let me look again and see if I missed something obvious in lua posix to write to an open file descriptor before we spend too much more time on this

It could still be something that I did causing this problem. But I will appreciate you looking into this. In the meantime, I already have the stdout trick above which is working so I will use that to make some more progress on `flux-job-debug`

**Comment by grondo** [comment]
Oh, duh. There is a `posix.write()` call we can use. I'll try updating my branch with that approach.

**Comment by dongahn** [comment]
Oh! Sounds promising.

**Comment by grondo** [comment]
Ok, try the latest version of that branch, which includes this change
```diff
diff --git a/src/cmd/flux-wreckrun b/src/cmd/flux-wreckrun
index 16ee520..9497378 100755
--- a/src/cmd/flux-wreckrun
+++ b/src/cmd/flux-wreckrun
@@ -184,16 +184,10 @@ if not jobid then wreck:die ("%s\n", err) end
 
 wreck:verbose ("%4.03fs: Registered jobid %d\n", tt:get0(), jobid)
 
-local jobid_fd = os.getenv ("FLUX_WRECKRUN_JOBID_FD")
+local jobid_fd = tonumber (os.getenv ("FLUX_WRECKRUN_JOBID_FD"))
 if jobid_fd then
-    local f,err = io.open ("/proc/self/fd/"..jobid_fd, "w")
-    if f then
-        f:write (jobid.."\n")
-        f:close ()
-    else
-        wreck:say ("Error: opening FLUX_WRECKRUN_JOBID_FD=%d: %s\n",
-                   jobid_fd, err)
-    end
+    posix.write (jobid_fd, jobid.."\n")
+    posix.close (jobid_fd)
 end

```

**Comment by dongahn** [comment]
> Ok, try the latest version of that branch, which includes this change

I tested this in my environment and this seems to work great! Thank you for finding `posix.write`!

**Comment by dongahn** [comment]
I assume there is no action item on the flux handle attributes of flux handle and close this ticket. If not, please let me know.
