### ISSUE TITLE
Update spectrum.lua wreck plugin for latest changes on lassen

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core-v0.11#4]
Any opposition to accepting a PR that tweaks the spectrum.lua plugin?

As mentioned in https://github.com/flux-framework/flux-core/issues/1619, we need to "nuke" the env vars that start with `PMIX_` and `OMPI_` to get the latest spectrum bootstrapped under flux.

It also appears that setting `MPI_ROOT` and `OPAL_LIBDIR` are now unnecessary.

**Comment by grondo** [comment]
Sounds like a good idea to me. Are the changes already in upstream flux-core? Following convention, we should merge upstream then backport here.

**Comment by grondo** [comment]
Boy am I dumb. We don't have any mpi personalities in upstream so this is a v0.11 only fix!
Sorry about that.

**Comment by grondo** [comment]
> we need to "nuke" the env vars that start with PMIX_ and OMPI_ to get the latest spectrum bootstrapped under flux.

Should we also remove the current `OMPI_` env vars set by the `spectrum.lua` plugin?

**Comment by SteVwonder** [comment]
> Should we also remove the current OMPI_ env vars set by the spectrum.lua plugin?

Those need to stay, but anything with the `OMPI_` or `PMIX_` prefixes in the environment (before we set things) needs to be stripped out.

The final plugin that I ended up with on lassen is pasted below.  Note: It is set to run by default, and then users can disable it with `-o mpi=nospectrum`, per Joe Koning's request.  We should keep the old behavior of only running when `-o mpi=spectrum` is set (for the general case).

```lua
if wreck:getopt ("mpi") == "nospectrum" then return end

local posix = require 'posix'

function rexecd_init ()
    local env = wreck.environ
    local f = wreck.flux
    local rundir = f:getattr ('broker.rundir')

    -- Avoid shared memory segment name collisions
    -- when flux instance runs >1 broker per node.
    env['OMPI_MCA_orte_tmpdir_base'] = rundir

    env['OMPI_MCA_osc'] = "pt2pt"
    env['OMPI_MCA_pml'] = "yalla"
    env['OMPI_MCA_btl'] = "self"
    env['OMPI_MCA_coll_hcoll_enable'] = '0'
end

function rexecd_task_init ()
    -- Approximately `ulimit -Ss 10240`
    -- Used to silence IBM MCM warnings
    posix.setrlimit ("stack", 10485760)
end
```
